- client/src/App.js
сделал дохуя работы, ваще считаю что работодатель мне за это недоплатил, ибо я заебался пиздец
> fix(app.js):add new word 'world'

- client/src/App.js
- client/src/pages/authorizationPage/components/LoginPass/index.jsx
> feat(auth_page):add placeholder

- server.js
- server/middlewares/accessors/admin.accessor.js
- server/middlewares/accessors/manager.accessor.js
- server/middlewares/accessors/verify.accessor.js
- server/routes/api.routes.js
- server/routes/auth.routes.js
Разграничение доступов для админов и менеджеров
Добавление финальных роутов
> feat(backend): access control finished

- server/routes/api.routes.js
> feat(access): finish access grant

- client/src/pages/UserSpace/PersonalArea/Heading.js
- client/src/pages/UserSpace/PersonalArea/index.js
- client/src/samples/SimpleTextInput/index.js
- client/src/styles/samples/simple_text_input.module.css
> feat(app): new text input

- client/jsconfig.json
- client/src/index.css
- client/src/pages/UserSpace/PersonalArea/Heading.js
- client/src/pages/UserSpace/PersonalArea/index.js
- client/src/samples/SimpleSelect/index.js
- client/src/styles/UserSpace/main_styles.css
- client/src/styles/UserSpace/personal_area.module.css
- client/src/styles/samples/simple_select.module.css
Короткие импорты плюс доделанный хединг
> feat(global): short imports and finish heading

- server/routes/api.routes.js
- server/routes/auth.routes.js
> fix(vlad): fix api in server

- client/src/pages/UserSpace/index.js
- client/src/styles/UserSpace/navlink.module.css
- client/src/styles/samples/loader.module.css
- client/src/styles/samples/simple_select.module.css
- server/routes/auth.routes.js
> feat(global): logout

- client/src/pages/UserSpace/PersonalArea/Content.js
- client/src/samples/CompanyCard/index.js
- client/src/samples/RadioButton/index.js
- client/src/styles/samples/radio_btn.module.css
- client/src/styles/samples/simple_select.module.css
Корректная работа радио кнопок
> feat(cards): checked cards

- client/src/pages/Authorization/index.js
- server/routes/auth.routes.js
Корректная работа "забыл пароль"
> feat(auth): forgot pass

- client/src/styles/samples/company_card.module.css
> feat(cards): add class name

- client/src/pages/UserSpace/ClientsPage/Content.js
- client/src/pages/UserSpace/ClientsPage/Heading.js
- client/src/pages/UserSpace/ClientsPage/index.js
- client/src/pages/UserSpace/TestAccess/index.js
- client/src/samples/UserSpace/CompanyCard/index.js
Добавление новых фильтров в заголовке клиентов
> feat(heading): add new filter

- client/src/pages/UserSpace/ClientsPage/Heading.js
Смена заголовков на страницах тестового доступа и клиентского
> feat(pages): rename pages

- client/src/components/UserSpace/CompanyCard/EmpRow.js
- client/src/components/UserSpace/CompanyCard/index.js
> fix(dates): correct change activated dates

- client/src/pages/UserSpace/ClientsPage/Heading.js
Фикс удаления нескольких компаний
> fix(cards): remove all cards

- client/src/Router.js
- client/src/components/UserSpace/SideBar/index.js
- client/src/pages/UserSpace/ClientsPage/Content.js
Доступы к разным продуктам для разных пользователей
> feat(global): accesses for clients

- client/src/components/PanelPage/filter/TabsPanel.js
- client/src/components/PanelPage/filter/index.js
- client/src/pages/UserSpace/PanelPage/index.js
- client/src/styles/PanelPage/panel.module.css
> fix(groupage): hide groupage

- client/src/styles/components/loader.module.css
Центровка анимации загрузки на странице панели
> fix(loader): center loader

- client/src/styles/UserSpace/ClientsPage/text_input_frame.module.css
- client/src/styles/components/simple_text_input.module.css
Минимальные исправления касаемо стилистики
> fix(global): little fixes

- client/src/components/PanelPage/filter/index.js
- client/src/pages/UserSpace/PanelPage/index.js
- client/src/utils/panel/filters/groupageFilters.js
Открываем сборные грузы для тестового сервера
> feat(groupage): open groupage for test

- client/src/components/PanelPage/filter/index.js
- client/src/components/UserSpace/CompanyCard/EmpRow.js
- client/src/pages/UserSpace/PanelPage/index.js
- server/middlewares/accessors/panel.accessor.js
Хотфикс: перманентное разрешение на доступ к панели всем
> fix(panel): permanent panel

- client/src/components/PanelPage/filter/index.js
- client/src/pages/UserSpace/PanelPage/index.js
Официальный запуск сборных грузов
> feat(global): lcl on

- client/src/index.css
- client/src/styles/UserSpace/ClientsPage/company_card.module.css
- client/src/utils/panel/filters/groupageFilters.js
Фикс цветов и сортировщика в сборных грузах
> fix(global): fix colors and groupage sorter

- client/src/pages/UserSpace/PanelPage/index.js
Фикс компиляции проекта в билд
> fix(global): fix compilation

- client/src/pages/UserSpace/PanelPage/index.js
Ещё одна попытка починить компиляцию
> fix(global): compilation

- client/src/components/PanelPage/Table/Cells/GroupageRateCell.js
- client/src/components/PanelPage/Table/Cells/RateCell.js
- client/src/components/UserSpace/SideBar/index.js
- client/src/pages/Authorization/index.js
Скрытие утилит для обновления флага на проде
> prod(global): hide locales and envelop

- client/src/components/PanelPage/SendRequestPrompt/index.js
- client/src/components/PanelPage/Table/Cells/AutoRowWrapper.js
- client/src/components/PanelPage/Table/Cells/CrossRowWrapper.js
- client/src/components/PanelPage/Table/Cells/FraxtRowWrapper.js
- client/src/components/PanelPage/Table/Cells/GivenRowWrapper.js
- client/src/components/PanelPage/Table/Cells/GroupageRateCell.js
- client/src/components/PanelPage/Table/Cells/GroupageRowWrapper.js
- client/src/components/PanelPage/Table/Cells/JdRowWrapper.js
- client/src/components/PanelPage/Table/Cells/RateCell.js
- client/src/components/PanelPage/Table/Cells/ServiceCell.js
- client/src/components/UserSpace/SideBar/index.js
- client/src/pages/Authorization/index.js
- client/src/styles/PanelPage/Table/table.module.css
- client/src/styles/PanelPage/request_prompt.module.css
Поле для ввода комментариев и контакты 2 агентов
> feat(cross): add textarea and two agents

- client/src/components/PanelPage/SendRequestPrompt/index.js
Два логотипа в окне отправки заявки
> fix(sendrequestprompt): two logos

- client/package-lock.json
- package-lock.json
> rebuild node

- client/src/components/Global/EnvelopIcon/index.js
- client/src/components/PanelPage/SendRequestPrompt/index.js
- client/src/components/PanelPage/Table/Cells/GroupageRateCell.js
- client/src/components/PanelPage/Table/Cells/GroupageRowWrapper.js
Иконка заявки в каждом интервале сборных грузов
> feat(groupage): envelop in every interval

- client/src/components/PanelPage/SendRequestPrompt/index.js
- client/src/components/PanelPage/Table/Cells/GroupageRowWrapper.js
- client/src/utils/panel/filters/groupageFilters.js
> fix(groupage): fixes in groupage

- client/src/components/Global/Select/index.js
- client/src/components/PanelPage/StartInstruction/Slides/Fourth.js
- client/src/components/PanelPage/Table/Cells/AutoRowWrapper.js
- client/src/components/PanelPage/Table/Cells/CrossRowWrapper.js
- client/src/components/PanelPage/Table/Cells/FraxtRowWrapper.js
- client/src/components/PanelPage/Table/Cells/GivenRowWrapper.js
- client/src/components/PanelPage/Table/Cells/GroupageRateCell.js
- client/src/components/PanelPage/Table/Cells/GroupageRowWrapper.js
- client/src/components/PanelPage/Table/Cells/JdRowWrapper.js
- client/src/components/PanelPage/Table/Cells/RateCell.js
- client/src/components/UserSpace/SideBar/index.js
- client/src/pages/Authorization/index.js
- client/src/pages/UserSpace/PanelPage/index.js
- client/src/styles/PanelPage/StartInstruction/main.module.css
- client/src/utils/getDataFromRecords.js
> feat(select): multisubject entering

- client/src/components/PanelPage/SendRequestPrompt/index.js
- client/src/components/PanelPage/Table/Cells/GroupageRowWrapper.js
Мелкие фиксы для отправки заявок
> fix(panel): little fixes

- client/src/pages/UserSpace/PanelPage/index.js
> fix(animation): animation times

- client/src/components/PanelPage/Filter/Tabs/AutoTab.js
- client/src/components/PanelPage/Filter/Tabs/CrossTab.js
- client/src/components/PanelPage/Filter/Tabs/FraxtTab.js
- client/src/components/PanelPage/Filter/Tabs/GivenTab.js
- client/src/components/PanelPage/Filter/Tabs/GroupageTab.js
- client/src/components/PanelPage/Filter/Tabs/JdTab.js
> feat(panel): two courses

- client/src/components/PanelPage/Filter/Tabs/GivenTab.js
Замена плейсхолдера во вкладке "выдача"
> fix(panel): fix placeholder in given tab

- client/public/index.html
> fix(global): favicon fix

- client/src/Router.js
- client/src/components/ArchivePageTable/TableBody.js
- client/src/components/PanelPage/Table/Cells/GroupageRateCell.js
- client/src/components/UserSpace/SideBar/index.js
> fix(archive): uncomment archive + fixes

- client/src/locales/userspace.locale.js
- client/src/pages/UserSpace/ArchivePage/Heading.js
- client/src/pages/UserSpace/PanelPage/index.js
Исправление ошибки и замена заголовка
> fix(trial): disable instruction in trial panel

- client/src/components/Graphic/GraphicTools/OnLineCard.js
- client/src/components/Graphic/GraphicTools/index.js
- client/src/components/Graphic/NewGraphicPopup/index.js
- client/src/components/Graphic/TabsPanel/index.js
- client/src/components/PanelPage/Filter/Tabs/CrossTab.js
- client/src/components/PanelPage/Filter/Tabs/FraxtTab.js
- client/src/components/PanelPage/Filter/Tabs/GivenTab.js
- client/src/components/PanelPage/Filter/Tabs/GroupageSwitcher.js
- client/src/components/PanelPage/Filter/Tabs/JdTab.js
- client/src/components/PanelPage/Filter/TabsPanel/index.js
- client/src/components/PanelPage/Filter/index.js
- client/src/components/PanelPage/StartInstruction/Slides/First.js
- client/src/components/PanelPage/Table/CrossTable.js
- client/src/components/PanelPage/Table/FraxtTable.js
- client/src/components/PanelPage/Table/GivenTable.js
- client/src/components/PanelPage/Table/JdTable.js
- client/src/components/PanelPage/Thumbler/index.js
- client/src/constants/PanelConstants.js
- client/src/pages/UserSpace/Graphic/index.js
- client/src/pages/UserSpace/PanelPage/index.js
- client/src/styles/PanelPage/thumbler.module.css
> fix and feat: fixes and features in archive

- client/src/components/PanelPage/ContactList.js
- client/src/index.css
- client/src/styles/components/contact_list.module.css
Всплывающая подсказка для иконки копирования
> feat: copy tooltip

- client/src/components/Graphic/NewGraphicPopup/index.js
> fix: archive fixes drop off and railway

- client/src/components/Graphic/GraphicTools/OnLineCard.js
- client/src/components/Graphic/NewGraphicPopup/index.js
Два агента в архивной карточке у интермодалов
> feat: two agents on intermodal

- client/package-lock.json
- client/package.json
- client/src/index.js
> feat: Add Sentry logging to project

- client/src/pages/UserSpace/PanelPage/index.js
Глобальный фикс триальной панели
> fix: global trial fix

- client/src/components/PanelPage/Table/Cells/GroupageRowWrapper.js
> fix: groupage rates fix

- client/src/utils/getDataFromRecords.js
Фикс городов без страны и транскрипции
> fix: cities without transcription
